{
    "playbook": "
---
- hosts: all
  remote_user: root
  gather_facts: false
  vars:
    name_JMS_queue: \"{{ jms_queue }}\",
    select_queue: \"{{ queue }}\",
    select_subdeployment: \"{{ subdeployment }}\"
  tasks:
    - name: Create a subdeployment
      ping:
    - pause:
        seconds: 5",
    "hosts": {
        "node": {
            "hosts": ["127.0.0.1"],
            "vars": {"ansible_connection": "local"}
        }
    },
    "options": {
      "async": false,
      "extra_vars": "jms_queue=TestJMSQueue", "queue=jms/TestJMSQueue", "subdeployment=TestSubdeployment",
      "skip_tags": "reboot"
    }
}